---
# This config uses the QMC5883L, a triple-axis magnetometer, to read your water meter or gas meter.

substitutions:
  # water or gas
  device_class: 'water'

  # mdi:water or mdi:meter-gas
  device_icon: 'mdi:water'

  # For water one of: CCF, ft³, gal, L, m³
  # For gas one of: CCF, ft³, m³
  volume_unit: 'gal'

  i2c_scl: GPIO5  # D1
  i2c_sda: GPIO4  # D2

  # Set these only if you have connected two QMC5883L to one device, see esphome-two-meters.yaml
  prefix_name: ''
  prefix_id: ''

  qmc5883l_update_interval: '5ms'
  qmc5883l_oversampling: '64x'

  volume_per_half_rotation_initial_value: '0.01008156'
  flow_update_interval_seconds: '10'

  hide_magnetic_field_strength_sensors: 'true'
  hide_half_rotations_total_sensor: 'true'

esphome:
  min_version: "2024.4.0" # This version includes https://github.com/esphome/esphome/pull/6456
  # Default loop interval is 16ms. Setting it to 0 to make updates faster.
  # Without setting this, the actual update interval of qmc5883l is: 6ms on ESP32, 10ms on ESP8266.
  # With this, it's 5ms on ESP32, 8ms on ESP8266.
  on_boot:
    then:
      - lambda: App.set_loop_interval(0);

logger:
  level: INFO
  logs:
    qmc5883l: INFO

api:
  services:
    # Based on https://esphome.io/components/sensor/pulse_meter.html#re-setting-the-total-pulse-count
    # Useful if you would like the total sensor to match what you see on your meter you are trying to match.
    - service: ${prefix_id}set_total
      variables:
        new_total: float
      then:
        - globals.set:
            id: ${prefix_id}half_rotations_total
            value: !lambda 'return new_total / id(${prefix_id}volume_per_half_rotation).state;'

globals:
  - id: ${prefix_id}half_rotations_total
    type: long
    restore_value: yes
    initial_value: '0'
  - id: ${prefix_id}axis_value_high
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: ${prefix_id}calibrating
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: ${prefix_id}calibrating_min
    type: float
    restore_value: no
  - id: ${prefix_id}calibrating_max
    type: float
    restore_value: no

number:
  - platform: template
    id: ${prefix_id}volume_per_half_rotation
    name: ${prefix_name}Volume per half rotation
    entity_category: config
    mode: box
    min_value: 0
    max_value: 9999999
    step: 0.000000001
    initial_value: ${volume_per_half_rotation_initial_value}
    update_interval: never
    restore_value: true
    optimistic: true
    unit_of_measurement: ${volume_unit}

  - platform: template
    id: ${prefix_id}temperature_offset
    name: ${prefix_name}Temperature Offset
    unit_of_measurement: '°C'
    min_value: -100
    max_value: 100
    step: 0.1
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 33
    icon: 'mdi:thermometer'
    entity_category: config

  - platform: template
    id: ${prefix_id}threshold_lower
    name: ${prefix_name}Threshold lower
    entity_category: config
    mode: box
    min_value: -9999
    max_value: 9999
    step: 0.1
    initial_value: -9999
    update_interval: never
    restore_value: true
    optimistic: true
    unit_of_measurement: µT

  - platform: template
    id: ${prefix_id}threshold_upper
    name: ${prefix_name}Threshold upper
    entity_category: config
    mode: box
    min_value: -9999
    max_value: 9999
    step: 0.1
    initial_value: 9999
    update_interval: never
    restore_value: true
    optimistic: true
    unit_of_measurement: µT

  - platform: template
    id: ${prefix_id}calibration_seconds
    name: ${prefix_name}Calibration time
    entity_category: config
    icon: mdi:timer
    mode: box
    min_value: 1
    max_value: 999
    step: 1
    initial_value: 5
    update_interval: never
    restore_value: true
    optimistic: true
    unit_of_measurement: s

button:
  - platform: template
    id: ${prefix_id}calibrate_button
    name: ${prefix_name}Calibrate axis
    entity_category: config
    on_press:
      - lambda: |-
          ESP_LOGI("calibration", "Starting calibration. Make sure ${device_class} is running");
          id(${prefix_id}calibrating_min) = std::numeric_limits<float>::max();
          id(${prefix_id}calibrating_max) = std::numeric_limits<float>::lowest();
          id(${prefix_id}calibrating) = true;
      - delay: !lambda return id(${prefix_id}calibration_seconds).state * 1000;
      - lambda: |-
          id(${prefix_id}calibrating) = false;
          float range = id(${prefix_id}calibrating_max) - id(${prefix_id}calibrating_min);
          if (range < 0) {
            ESP_LOGW("${prefix_id}calibration", "Didn't get any values.");
          } else {
            ESP_LOGI("${prefix_id}calibration", "ranged from %.2f to %.2f",
                     id(${prefix_id}calibrating_min), id(${prefix_id}calibrating_max));
          }
          float min, max;
          if (range > 20) {
            min = id(${prefix_id}calibrating_min);
            max = id(${prefix_id}calibrating_max);
          } else {
            ESP_LOGE("${prefix_id}calibration", "Calibration failed. Magnitude did not have a range of at least 20");
            return;
          }
          float lower_threshold = min + (max - min) / 2 - 5;
          float upper_threshold = min + (max - min) / 2 + 5;
          ESP_LOGI("${prefix_id}calibration", "Selected lower threshold: %.2f and upper threshold: %.2f", lower_threshold, upper_threshold);
          id(${prefix_id}threshold_lower).make_call().set_value(roundf(lower_threshold * 10) / 10).perform();
          id(${prefix_id}threshold_upper).make_call().set_value(roundf(upper_threshold * 10) / 10).perform();

i2c:
  - id: ${prefix_id}i2c_bus
    scl: ${i2c_scl}
    sda: ${i2c_sda}
    frequency: 50kHz
    scan: false

sensor:
  # Holds the magnetic field strength value of x, y, or z depending on the axis template select.
  # Increments counters when value crosses thresholds.
  - platform: template
    id: ${prefix_id}magnitude
    name: ${prefix_name}Magnetic Field Strength Magnitude
    internal: ${hide_magnetic_field_strength_sensors}
    entity_category: diagnostic
    lambda: |-
      float x2 = id(${prefix_id}qmc5883l_axis_x).state * id(${prefix_id}qmc5883l_axis_x).state;
      float y2 = id(${prefix_id}qmc5883l_axis_y).state * id(${prefix_id}qmc5883l_axis_y).state;
      float z2 = id(${prefix_id}qmc5883l_axis_z).state * id(${prefix_id}qmc5883l_axis_z).state;
      return x2 + y2 + z2; // Avoid sqrt for performance
    on_raw_value:
      then:
        - lambda: |-
            if (x > id(${prefix_id}threshold_upper).state && !id(${prefix_id}axis_value_high)) {
              id(${prefix_id}axis_value_high) = true;
              id(${prefix_id}half_rotations_total) += 1;
              id(led).turn_on();
              // Update total and flow sensors
              id(${prefix_id}sensor_half_rotations_total).update();
              id(${prefix_id}sensor_flow).update();
            } else if (x < id(${prefix_id}threshold_lower).state && id(${prefix_id}axis_value_high)) {
              id(${prefix_id}axis_value_high) = false;
              id(led).turn_off();
            }
    filters:
      - delta: 3

  # https://esphome.io/components/sensor/qmc5883l.html
  - platform: qmc5883l
    id: ${prefix_id}qmc5883l_id
    i2c_id: ${prefix_id}i2c_bus
    address: 0x0D
    oversampling: ${qmc5883l_oversampling}
    update_interval: ${qmc5883l_update_interval}

    field_strength_x:
      id: ${prefix_id}qmc5883l_axis_x
      name: ${prefix_name}Magnetic Field Strength X
      internal: ${hide_magnetic_field_strength_sensors}
      entity_category: diagnostic
      filters:
        - delta: 3
      on_value:
        then:
          - component.update: ${prefix_id}magnitude
      
    field_strength_y:
      id: ${prefix_id}qmc5883l_axis_y
      name: ${prefix_name}Magnetic Field Strength Y
      internal: ${hide_magnetic_field_strength_sensors}
      entity_category: diagnostic
      filters:
        - delta: 3
      on_value:
        then:
          - component.update: ${prefix_id}magnitude

    field_strength_z:
      id: ${prefix_id}qmc5883l_axis_z
      name: ${prefix_name}Magnetic Field Strength Z
      internal: ${hide_magnetic_field_strength_sensors}
      entity_category: diagnostic
      filters:
        - delta: 3
      on_value:
        then:
          - component.update: ${prefix_id}magnitude
  
    temperature:
      id: ${prefix_id}qmc5883l_temperature
      name: ${prefix_name}Temperature
      filters:
        - lambda: "return x + id(${prefix_id}temperature_offset).state;"
        - sliding_window_moving_average:
            window_size: 3000
            send_every: 3000
        - or:
            - throttle: 300s
            - delta: 0.5

  - platform: template
    id: ${prefix_id}sensor_half_rotations_total
    name: ${prefix_name}Half rotations total
    lambda: return id(${prefix_id}half_rotations_total);
    update_interval: never
    internal: ${hide_half_rotations_total_sensor}
    entity_category: diagnostic
    accuracy_decimals: 0
    state_class: 'total_increasing'
    icon: 'mdi:counter'
    on_value:
      then:
        - component.update: ${prefix_id}sensor_total

  - platform: template
    id: ${prefix_id}sensor_total
    name: ${prefix_name}Total
    lambda: return id(${prefix_id}half_rotations_total) * id(${prefix_id}volume_per_half_rotation).state;
    update_interval: never
    accuracy_decimals: 2
    device_class: ${device_class}
    icon: ${device_icon}
    state_class: total_increasing
    unit_of_measurement: ${volume_unit}

  - platform: template
    id: ${prefix_id}sensor_flow
    name: ${prefix_name}Flow
    lambda: |-
      static float last_timestamp = 0;
      struct timeval;
      gettimeofday(&timeval, NULL);
      float timestamp = timeval.tv_sec + timeval.tv_usec / 1e6;
      float flow = id(${prefix_id}volume_per_half_rotation).state * 60.0 / (timestamp - last_timestamp);
      ESP_LOGI("${prefix_id}sensor_flow", "Timestamp %.3f, last: %.3f, delta: %.3f, flow: %.2f", timestamp, last_timestamp, timestamp-last_timestamp, flow);
      last_timestamp = timestamp;
      return flow;
    update_interval: never
    accuracy_decimals: 2
    state_class: measurement
    unit_of_measurement: ${volume_unit}/min
